
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombree = new javax.swing.JTextField();
        tf_presupuesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sp_copas = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tf_estadio = new javax.swing.JTextField();
        jb_agregarequipo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_nombrej = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_posicion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        tf_habilidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_tecnica = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_resistencia = new javax.swing.JTextField();
        jb_agregarjugador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_equipo = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_jugador = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        bg_disponibilidad = new javax.swing.ButtonGroup();
        jd_comprar = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_jugador2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        j_arbol = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();
        pp_menu = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        pp_menu2 = new javax.swing.JPopupMenu();
        Eliminar2 = new javax.swing.JMenuItem();
        Modificar2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Nombre");

        jLabel4.setText("Presupuesto");

        jLabel5.setText("Copas");

        jLabel6.setText("Estadio");

        jb_agregarequipo.setText("Agregar equipo");
        jb_agregarequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarequipoMouseClicked(evt);
            }
        });

        jLabel7.setText("Nombre");

        jLabel8.setText("Precio");

        jLabel9.setText("Posicion");

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atacante", "Mediocampista", "Defensa", "Portero", " " }));

        jLabel10.setText("Disponibilidad");

        bg_disponibilidad.add(rb1);
        rb1.setSelected(true);
        rb1.setText("Disponible");

        bg_disponibilidad.add(rb2);
        rb2.setText("No Disponible");

        jLabel11.setText("Habilidad");

        jLabel12.setText("Tecnica");

        jLabel13.setText("Resistencia");

        jb_agregarjugador.setText("Agregar Jugador");
        jb_agregarjugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarjugadorMouseClicked(evt);
            }
        });

        jl_equipo.setModel(new DefaultListModel());
        jl_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_equipoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_equipo);

        jLabel14.setText("Lista de equipos");

        jl_jugador.setModel(new DefaultListModel());
        jl_jugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_jugadorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_jugador);

        jLabel15.setText("Lista de jugadores");

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nombree, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp_copas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jb_agregarequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(27, 27, 27)
                                .addComponent(rb1)
                                .addGap(18, 18, 18)
                                .addComponent(rb2))
                            .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_agregarLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_posicion, 0, 174, Short.MAX_VALUE))
                                .addGroup(jd_agregarLayout.createSequentialGroup()
                                    .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_nombrej)
                                        .addComponent(tf_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(tf_resistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_habilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(tf_tecnica)))
                            .addComponent(jb_agregarjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombrej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sp_copas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(rb1)
                    .addComponent(rb2))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_habilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_agregarequipo)
                    .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(tf_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_resistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jb_agregarjugador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(41, 41, 41))
        );

        jl_jugador2.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_jugador2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Liga Española");
        j_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(j_arbol);

        jButton2.setText("Comprar jugador seleccionado");

        javax.swing.GroupLayout jd_comprarLayout = new javax.swing.GroupLayout(jd_comprar.getContentPane());
        jd_comprar.getContentPane().setLayout(jd_comprarLayout);
        jd_comprarLayout.setHorizontalGroup(
            jd_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_comprarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jd_comprarLayout.setVerticalGroup(
            jd_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_comprarLayout.createSequentialGroup()
                .addGroup(jd_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_comprarLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jd_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_comprarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_comprarLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton2)))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        pp_menu.add(Eliminar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        pp_menu.add(Modificar);

        Eliminar2.setText("Eliminar");
        Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar2ActionPerformed(evt);
            }
        });
        pp_menu2.add(Eliminar2);

        Modificar2.setText("Modificar");
        pp_menu2.add(Modificar2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(455, 455, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Liga Española Online");

        jButton1.setText("Agregar a la lista y al arbol");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Comprar un jugador");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fut.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_agregar.pack();
        jd_agregar.setModal(true);
        jd_agregar.setLocationRelativeTo(this);
        jd_agregar.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        jd_comprar.pack();
        jd_comprar.setModal(true);
        jd_comprar.setLocationRelativeTo(this);
        jd_comprar.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    @SuppressWarnings("unchecked")
    private void jb_agregarequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarequipoMouseClicked
        DefaultListModel modelo = (DefaultListModel) jl_equipo.getModel();
        modelo.addElement(new Equipo(tf_nombree.getText(),Double.parseDouble(tf_presupuesto.getText()),(Integer)sp_copas.getValue(),tf_estadio.getText()));
        DefaultTreeModel m=(DefaultTreeModel)j_arbol.getModel();
        DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)m.getRoot();
        DefaultMutableTreeNode nodo_equipo;
        nodo_equipo=new DefaultMutableTreeNode(new Equipo(tf_nombree.getText(),Double.parseDouble(tf_presupuesto.getText()),(Integer)sp_copas.getValue(),tf_estadio.getText()));
        raiz.add(nodo_equipo);
        m.reload();
        jl_equipo.setModel(modelo);
        tf_nombree.setText("");
        tf_presupuesto.setText("");
        sp_copas.setValue(0);
        tf_estadio.setText(""); 

    }//GEN-LAST:event_jb_agregarequipoMouseClicked

    @SuppressWarnings("unchecked")
    private void jb_agregarjugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarjugadorMouseClicked
       DefaultListModel modelo=(DefaultListModel)jl_jugador.getModel();
       String disponible="";
       if(rb1.isSelected()){
           disponible="disponible";
       }
       if(rb2.isSelected()){
           disponible="no disponible";
       }
       modelo.addElement(new Jugador(tf_nombrej.getText(),Double.parseDouble(tf_precio.getText()),(String)cb_posicion.getSelectedItem(),disponible,Integer.parseInt(tf_habilidad.getText()),Integer.parseInt(tf_tecnica.getText()),Integer.parseInt(tf_resistencia.getText())));
       jl_jugador.setModel(modelo);
       jl_jugador2.setModel(modelo);
       tf_nombrej.setText("");
       tf_precio.setText("");
       tf_habilidad.setText("");
       tf_resistencia.setText("");
       tf_tecnica.setText("");
       cb_posicion.setSelectedIndex(0);
       
    }//GEN-LAST:event_jb_agregarjugadorMouseClicked

    private void jl_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_equipoMouseClicked
        if(evt.isMetaDown()){
            
            pp_menu.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_jl_equipoMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int resp=JOptionPane.showConfirmDialog(jd_agregar,"seguro que desea eliminar","confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resp==JOptionPane.OK_OPTION){
            DefaultListModel modelo=(DefaultListModel)jl_equipo.getModel();
            
            modelo.remove(jl_equipo.getSelectedIndex());
           
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void jl_jugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_jugadorMouseClicked
        if(evt.isMetaDown()){
            
            pp_menu2.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_jl_jugadorMouseClicked

    private void Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar2ActionPerformed
        int resp=JOptionPane.showConfirmDialog(jd_agregar,"seguro que desea eliminar","confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resp==JOptionPane.OK_OPTION){
            DefaultListModel modelo=(DefaultListModel)jl_jugador.getModel();
            
            modelo.remove(jl_jugador.getSelectedIndex());
           
        }
    }//GEN-LAST:event_Eliminar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Eliminar2;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenuItem Modificar2;
    private javax.swing.ButtonGroup bg_disponibilidad;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree j_arbol;
    private javax.swing.JButton jb_agregarequipo;
    private javax.swing.JButton jb_agregarjugador;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JDialog jd_comprar;
    private javax.swing.JList<Equipo> jl_equipo;
    private javax.swing.JList<String> jl_jugador;
    private javax.swing.JList<String> jl_jugador2;
    private javax.swing.JPopupMenu pp_menu;
    private javax.swing.JPopupMenu pp_menu2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JSpinner sp_copas;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_habilidad;
    private javax.swing.JTextField tf_nombree;
    private javax.swing.JTextField tf_nombrej;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_presupuesto;
    private javax.swing.JTextField tf_resistencia;
    private javax.swing.JTextField tf_tecnica;
    // End of variables declaration//GEN-END:variables
DefaultMutableTreeNode nodo_seleccionado;

}
